DefaultOptions = function() {
    return {"maxSelect": 4,
        "floorColor": "#001F3F",
        "wallColor": "#85144B",
        "wallWidth": 6,
        "doorWidth": 3,
        "doorColor": "#01FF70",
        "windowWidth": 2,
        "windowColor": "#FF851B",
        "zoomFactor": 1.1,
        "offsetX": 0,
        "offsetY": 0,
        "autoSelect": false,
        "defaultFloorHeight": 50,
        "pointColor": "#3D9970",
        "pointLineWidth": 3,
        "pointStrokeStyle": "#000",
        "selectedPointColor": "#FF4136",
        "selectedPointLineWidth": 3,
        "pointRadius":5,
        "pathPointRadius":15,
        "selectedPointStrokeStyle": "#000000"};
};